services:
  - type: web
    name: ozkanwood-backend
    env: python
    buildCommand: bash build.sh
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /usr/local/share/.cache/ms-playwright
    plan: free
